///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace gittest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the gittestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("14219e9f-0de7-4180-ba7c-9c3c33682f54")]
    public partial class gittestRepository : RepoGenBaseFolder
    {
        static gittestRepository instance = new gittestRepository();
        gittestRepositoryFolders.KeyPromptFormAppFolder _keypromptform;
        gittestRepositoryFolders.KeePassAppFolder _keepass;
        gittestRepositoryFolders.MainFormAppFolder _mainform;

        /// <summary>
        /// Gets the singleton class instance representing the gittestRepository element repository.
        /// </summary>
        [RepositoryFolder("14219e9f-0de7-4180-ba7c-9c3c33682f54")]
        public static gittestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public gittestRepository() 
            : base("gittestRepository", "/", null, 0, false, "14219e9f-0de7-4180-ba7c-9c3c33682f54", ".\\RepositoryImages\\gittestRepository14219e9f.rximgres")
        {
            _keypromptform = new gittestRepositoryFolders.KeyPromptFormAppFolder(this);
            _keepass = new gittestRepositoryFolders.KeePassAppFolder(this);
            _mainform = new gittestRepositoryFolders.MainFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("14219e9f-0de7-4180-ba7c-9c3c33682f54")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("c81179a1-5f54-4262-9b35-15675ecf796f")]
        public virtual gittestRepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }

        /// <summary>
        /// The KeePass folder.
        /// </summary>
        [RepositoryFolder("9af18fd6-ea7b-495a-a609-81f745352b01")]
        public virtual gittestRepositoryFolders.KeePassAppFolder KeePass
        {
            get { return _keepass; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("89df0c39-e17d-4c02-a53c-f54bfa6ccbd2")]
        public virtual gittestRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class gittestRepositoryFolders
    {
        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("c81179a1-5f54-4262-9b35-15675ecf796f")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _mbtnokInfo;
            RepoItemInfo _mbtncancelInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "c81179a1-5f54-4262-9b35-15675ecf796f", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "ee8ba6e7-2dc7-40b0-86b8-bbb2b9cf2467");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "e8c20c92-5e06-4d2d-aadc-741bb6255195");
                _mbtncancelInfo = new RepoItemInfo(this, "MBtnCancel", "button[@controlname='m_btnCancel']", 30000, null, "0038aac2-ab81-4cb5-8cf0-91fd0a51ad95");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c81179a1-5f54-4262-9b35-15675ecf796f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c81179a1-5f54-4262-9b35-15675ecf796f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("ee8ba6e7-2dc7-40b0-86b8-bbb2b9cf2467")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("ee8ba6e7-2dc7-40b0-86b8-bbb2b9cf2467")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("e8c20c92-5e06-4d2d-aadc-741bb6255195")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("e8c20c92-5e06-4d2d-aadc-741bb6255195")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }

            /// <summary>
            /// The MBtnCancel item.
            /// </summary>
            [RepositoryItem("0038aac2-ab81-4cb5-8cf0-91fd0a51ad95")]
            public virtual Ranorex.Button MBtnCancel
            {
                get
                {
                    return _mbtncancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnCancel item info.
            /// </summary>
            [RepositoryItemInfo("0038aac2-ab81-4cb5-8cf0-91fd0a51ad95")]
            public virtual RepoItemInfo MBtnCancelInfo
            {
                get
                {
                    return _mbtncancelInfo;
                }
            }
        }

        /// <summary>
        /// The KeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("9af18fd6-ea7b-495a-a609-81f745352b01")]
        public partial class KeePassAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new KeePass  folder.
            /// </summary>
            public KeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass", "/form[@title='KeePass']", parentFolder, 30000, null, true, "9af18fd6-ea7b-495a-a609-81f745352b01", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "0454b118-152e-4144-a938-fc0283064279");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9af18fd6-ea7b-495a-a609-81f745352b01")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9af18fd6-ea7b-495a-a609-81f745352b01")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("0454b118-152e-4144-a938-fc0283064279")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("0454b118-152e-4144-a938-fc0283064279")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("89df0c39-e17d-4c02-a53c-f54bfa6ccbd2")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _schliessenInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "89df0c39-e17d-4c02-a53c-f54bfa6ccbd2", "")
            {
                _schliessenInfo = new RepoItemInfo(this, "Schliessen", "?/?/button[@accessiblename='Schließen']", 30000, null, "9b3873b2-37b9-40f7-b450-38fe0f08570d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("89df0c39-e17d-4c02-a53c-f54bfa6ccbd2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("89df0c39-e17d-4c02-a53c-f54bfa6ccbd2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Schliessen item.
            /// </summary>
            [RepositoryItem("9b3873b2-37b9-40f7-b450-38fe0f08570d")]
            public virtual Ranorex.Button Schliessen
            {
                get
                {
                    return _schliessenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Schliessen item info.
            /// </summary>
            [RepositoryItemInfo("9b3873b2-37b9-40f7-b450-38fe0f08570d")]
            public virtual RepoItemInfo SchliessenInfo
            {
                get
                {
                    return _schliessenInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}